# Generated by Django 3.0.8 on 2020-07-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_section'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='class',
            table='Class',
        ),
    ]
