# Generated by Django 3.0.8 on 2020-07-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200727_1747'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='section',
            table='Section',
        ),
    ]
