# Generated by Django 3.0.8 on 2020-08-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200803_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_all_users', 'Can view all users'), ('change_all_users', 'Can change all users'), ('add_all_user', 'Can change all users'), ('remove_all_users', 'Can change all users'), ('view_all_teachers', 'Can view all teachers'), ('change_all_teachers', 'Can change all teachers'), ('add_all_teachers', 'Can change all teachers'), ('remove_all_teachers', 'Can change all teachers'), ('view_all_students', 'Can view all students'), ('change_all_students', 'Can change all students'), ('add_all_students', 'Can change all students'), ('remove_all_students', 'Can change all students')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
