# Generated by Django 3.0.8 on 2020-07-27 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='Teacher',
        ),
    ]
